name: moinsen_physics
description: Just a simple physics game
publish_to: none
version: 0.2.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.21.0
  flame_forge2d: ^0.18.2+1
  flutter_sound: ^9.16.3
  permission_handler: ^11.3.0
  vector_math: ^2.1.4
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  logger: ^2.4.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
