name: moinsen_physics
description: Just a simple physics game
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.21.0
  flame_forge2d: ^0.18.2+1

  soundpool: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
